### ISSUE TITLE
Migrate hosting away from GH pages

### ISSUE THREAD

**Issue by arniemansell** [PyFlightCoach/FlightCoachScore#10]
Hi Tom,

I've done some reading up on Ionos hosting of static websites.  They come out OK in reviews and it'll cost me about 6 quid a month - but that does include the SSL certificate for fcscore.org as well which would cost a few quid per month anyway.  It'll give us at least 100GB of space, enough grunt and also a prototyping URL.  It also supports publishing from github - https://docs.ionos.space/docs/

Let me know what you think.

**Comment by ThomasDavid0** [comment]
Artur has kindly put it up here: now: https://flightcoach.org/fcscore/
I'll be making lots of updates over the next Month or so, is there any way we can publish the the flightcoach site from github actions?

**Comment by commsart** [comment]
Easy way to deploy client is to compress the build directory content, upload it to the website via cpanel and upack. Takes 3 min. I can provide Tom with the cpanel password (although you should have it).
