### ISSUE TITLE
paths

### ISSUE THREAD

**Issue by ThomasDavid0** [PyFlightCoach/FlightCoachScore#13]
from @commsart : need to change pycoach../FCScor... path to fcscoreclient on the website. Attempted to do that in the build files but it works only partially. May need ot be changed in the src first and rebuilt.

I assume the base path here has something to do with it: [https://github.com/PyFlightCoach/FlightCoachScore/blob/main/svelte.config.js](url)

**Comment by commsart** [comment]
resolved, commit pending
