### ISSUE TITLE
In flight list, wrong comment is shown

### ISSUE THREAD

**Issue by arniemansell** [PyFlightCoach/FlightCoachScore#38]
1. Bring up a flight list and find two flights with a comment
2. Click on one of the flights to see the detail
3. Now click on the other flight.  Its detail is shown, with correct manoeuvre scores etc, but the comment from the previous flight is shown.
4. Click on the flight twice more to close the detail and reopen the detail, correct comment is shown.

**Comment by ThomasDavid0** [comment]
Fixed with e777cd601fbe369b222cb00856f409f84e298a0f
